services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: planner-api-server
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=planner-db
    restart: always

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    volumes:
        - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres:
    name: planner-api-server
    
networks: 
  postgres-compose-network:
    driver: bridge